// Auto-generated extended skills list
export const allSkillsOptions = [
  { value: '3D Modeling', label: '3D Modeling' },
  { value: 'ASP.NET', label: 'ASP.NET' },
  { value: 'AWS', label: 'AWS' },
  { value: 'Account Management', label: 'Account Management' },
  { value: 'Accounting', label: 'Accounting' },
  { value: 'Adobe After Effects', label: 'Adobe After Effects' },
  { value: 'Adobe Illustrator', label: 'Adobe Illustrator' },
  { value: 'Adobe InDesign', label: 'Adobe InDesign' },
  { value: 'Adobe Lightroom', label: 'Adobe Lightroom' },
  { value: 'Adobe Photoshop', label: 'Adobe Photoshop' },
  { value: 'Adobe Premiere Pro', label: 'Adobe Premiere Pro' },
  { value: 'Adobe XD', label: 'Adobe XD' },
  { value: 'Agile', label: 'Agile' },
  { value: 'Alpine.js', label: 'Alpine.js' },
  { value: 'Android Development', label: 'Android Development' },
  { value: 'Angular', label: 'Angular' },
  { value: 'Animation', label: 'Animation' },
  { value: 'Ansible', label: 'Ansible' },
  { value: 'Ant Design', label: 'Ant Design' },
  { value: 'Apache', label: 'Apache' },
  { value: 'Appcelerator', label: 'Appcelerator' },
  { value: 'ArangoDB', label: 'ArangoDB' },
  { value: 'Artificial Intelligence', label: 'Artificial Intelligence' },
  { value: 'Assembly', label: 'Assembly' },
  { value: 'Auditing', label: 'Auditing' },
  { value: 'AutoCAD', label: 'AutoCAD' },
  { value: 'Axure', label: 'Axure' },
  { value: 'B2B Sales', label: 'B2B Sales' },
  { value: 'Babel', label: 'Babel' },
  { value: 'Backbone.js', label: 'Backbone.js' },
  { value: 'Backend Development', label: 'Backend Development' },
  { value: 'Balsamiq', label: 'Balsamiq' },
  { value: 'Big Data', label: 'Big Data' },
  { value: 'Blender', label: 'Blender' },
  { value: 'Blogging', label: 'Blogging' },
  { value: 'Bookkeeping', label: 'Bookkeeping' },
  { value: 'Bootstrap', label: 'Bootstrap' },
  { value: 'Brand Management', label: 'Brand Management' },
  { value: 'Business Development', label: 'Business Development' },
  { value: 'C#', label: 'C#' },
  { value: 'C++', label: 'C++' },
  { value: 'CI/CD', label: 'CI/CD' },
  { value: 'CakePHP', label: 'CakePHP' },
  { value: 'Cassandra', label: 'Cassandra' },
  { value: 'Chakra UI', label: 'Chakra UI' },
  { value: 'Chef', label: 'Chef' },
  { value: 'Cinema 4D', label: 'Cinema 4D' },
  { value: 'CircleCI', label: 'CircleCI' },
  { value: 'Cloud Security', label: 'Cloud Security' },
  { value: 'CodeIgniter', label: 'CodeIgniter' },
  { value: 'Communication', label: 'Communication' },
  { value: 'Compliance', label: 'Compliance' },
  { value: 'Computer Vision', label: 'Computer Vision' },
  { value: 'Confluence', label: 'Confluence' },
  { value: 'Content Marketing', label: 'Content Marketing' },
  { value: 'Copywriting', label: 'Copywriting' },
  { value: 'Cordova', label: 'Cordova' },
  { value: 'CorelDRAW', label: 'CorelDRAW' },
  { value: 'Corporate Finance', label: 'Corporate Finance' },
  { value: 'CouchDB', label: 'CouchDB' },
  { value: 'Couchbase', label: 'Couchbase' },
  { value: 'Critical Thinking', label: 'Critical Thinking' },
  { value: 'Cryptography', label: 'Cryptography' },
  { value: 'Customer Service', label: 'Customer Service' },
  { value: 'Customer Success', label: 'Customer Success' },
  { value: 'Cybersecurity', label: 'Cybersecurity' },
  { value: 'Dart', label: 'Dart' },
  { value: 'Data Analysis', label: 'Data Analysis' },
  { value: 'Data Entry', label: 'Data Entry' },
  { value: 'Data Mining', label: 'Data Mining' },
  { value: 'Data Science', label: 'Data Science' },
  { value: 'Database Management', label: 'Database Management' },
  { value: 'DaVinci Resolve', label: 'DaVinci Resolve' },
  { value: 'Deep Learning', label: 'Deep Learning' },
  { value: 'Digital Marketing', label: 'Digital Marketing' },
  { value: 'DigitalOcean', label: 'DigitalOcean' },
  { value: 'Django', label: 'Django' },
  { value: 'Docker', label: 'Docker' },
  { value: 'DynamoDB', label: 'DynamoDB' },
  { value: 'Editing', label: 'Editing' },
  { value: 'Elasticsearch', label: 'Elasticsearch' },
  { value: 'Ember.js', label: 'Ember.js' },
  { value: 'Email Marketing', label: 'Email Marketing' },
  { value: 'Employee Relations', label: 'Employee Relations' },
  { value: 'Ethical Hacking', label: 'Ethical Hacking' },
  { value: 'Event Planning', label: 'Event Planning' },
  { value: 'Excel', label: 'Excel' },
  { value: 'Express.js', label: 'Express.js' },
  { value: 'Facebook Ads', label: 'Facebook Ads' },
  { value: 'FastAPI', label: 'FastAPI' },
  { value: 'Figma', label: 'Figma' },
  { value: 'Final Cut Pro', label: 'Final Cut Pro' },
  { value: 'Financial Analysis', label: 'Financial Analysis' },
  { value: 'Financial Modeling', label: 'Financial Modeling' },
  { value: 'Firebase', label: 'Firebase' },
  { value: 'Firewalls', label: 'Firewalls' },
  { value: 'Flask', label: 'Flask' },
  { value: 'Flutter', label: 'Flutter' },
  { value: 'Forensics', label: 'Forensics' },
  { value: 'Frontend Development', label: 'Frontend Development' },
  { value: 'Game Development', label: 'Game Development' },
  { value: 'Git', label: 'Git' },
  { value: 'GitHub', label: 'GitHub' },
  { value: 'GitLab', label: 'GitLab' },
  { value: 'Go', label: 'Go' },
  { value: 'Google Ads', label: 'Google Ads' },
  { value: 'Google Analytics', label: 'Google Analytics' },
  { value: 'Google Cloud (GCP)', label: 'Google Cloud (GCP)' },
  { value: 'GraphQL', label: 'GraphQL' },
  { value: 'Groovy', label: 'Groovy' },
  { value: 'HIPAA', label: 'HIPAA' },
  { value: 'HTML', label: 'HTML' },
  { value: 'HBase', label: 'HBase' },
  { value: 'Hadoop', label: 'Hadoop' },
  { value: 'Haskell', label: 'Haskell' },
  { value: 'Heroku', label: 'Heroku' },
  { value: 'Human Resources', label: 'Human Resources' },
  { value: 'IAM', label: 'IAM' },
  { value: 'ISO 27001', label: 'ISO 27001' },
  { value: 'Incident Response', label: 'Incident Response' },
  { value: 'Information Security', label: 'Information Security' },
  { value: 'InVision', label: 'InVision' },
  { value: 'Inventory Management', label: 'Inventory Management' },
  { value: 'Investment Banking', label: 'Investment Banking' },
  { value: 'Ionic', label: 'Ionic' },
  { value: 'Java', label: 'Java' },
  { value: 'JavaScript', label: 'JavaScript' },
  { value: 'Jenkins', label: 'Jenkins' },
  { value: 'Jetpack Compose', label: 'Jetpack Compose' },
  { value: 'Jira', label: 'Jira' },
  { value: 'Kafka', label: 'Kafka' },
  { value: 'Keras', label: 'Keras' },
  { value: 'Koa', label: 'Koa' },
  { value: 'Kotlin', label: 'Kotlin' },
  { value: 'Kubernetes', label: 'Kubernetes' },
  { value: 'Laravel', label: 'Laravel' },
  { value: 'Lean Six Sigma', label: 'Lean Six Sigma' },
  { value: 'Linux', label: 'Linux' },
  { value: 'Logistics', label: 'Logistics' },
  { value: 'Looker', label: 'Looker' },
  { value: 'Lua', label: 'Lua' },
  { value: 'MATLAB', label: 'MATLAB' },
  { value: 'Machine Learning', label: 'Machine Learning' },
  { value: 'MariaDB', label: 'MariaDB' },
  { value: 'Market Research', label: 'Market Research' },
  { value: 'Marvel', label: 'Marvel' },
  { value: 'Material UI', label: 'Material UI' },
  { value: 'Maya', label: 'Maya' },
  { value: 'Memcached', label: 'Memcached' },
  { value: 'Meteor', label: 'Meteor' },
  { value: 'Microservices', label: 'Microservices' },
  { value: 'Microsoft Azure', label: 'Microsoft Azure' },
  { value: 'Microsoft Office', label: 'Microsoft Office' },
  { value: 'Microsoft SQL Server', label: 'Microsoft SQL Server' },
  { value: 'MongoDB', label: 'MongoDB' },
  { value: 'MySQL', label: 'MySQL' },
  { value: 'NLP', label: 'NLP' },
  { value: 'NativeScript', label: 'NativeScript' },
  { value: 'Negotiation', label: 'Negotiation' },
  { value: 'Neo4j', label: 'Neo4j' },
  { value: 'NestJS', label: 'NestJS' },
  { value: 'Netlify', label: 'Netlify' },
  { value: 'Network Security', label: 'Network Security' },
  { value: 'Next.js', label: 'Next.js' },
  { value: 'Nginx', label: 'Nginx' },
  { value: 'Node.js', label: 'Node.js' },
  { value: 'NumPy', label: 'NumPy' },
  { value: 'Nuke', label: 'Nuke' },
  { value: 'Nuxt.js', label: 'Nuxt.js' },
  { value: 'Objective-C', label: 'Objective-C' },
  { value: 'Onboarding', label: 'Onboarding' },
  { value: 'Operations Management', label: 'Operations Management' },
  { value: 'Oracle', label: 'Oracle' },
  { value: 'PCI DSS', label: 'PCI DSS' },
  { value: 'PHP', label: 'PHP' },
  { value: 'Pandas', label: 'Pandas' },
  { value: 'Payroll', label: 'Payroll' },
  { value: 'Penetration Testing', label: 'Penetration Testing' },
  { value: 'Performance Management', label: 'Performance Management' },
  { value: 'Perl', label: 'Perl' },
  { value: 'PhoneGap', label: 'PhoneGap' },
  { value: 'Photography', label: 'Photography' },
  { value: 'Podcasting', label: 'Podcasting' },
  { value: 'PostgreSQL', label: 'PostgreSQL' },
  { value: 'Power BI', label: 'Power BI' },
  { value: 'PowerShell', label: 'PowerShell' },
  { value: 'Problem Solving', label: 'Problem Solving' },
  { value: 'Procurement', label: 'Procurement' },
  { value: 'Product Management', label: 'Product Management' },
  { value: 'Project Management', label: 'Project Management' },
  { value: 'Prototyping', label: 'Prototyping' },
  { value: 'Public Relations', label: 'Public Relations' },
  { value: 'Public Speaking', label: 'Public Speaking' },
  { value: 'Puppet', label: 'Puppet' },
  { value: 'PyTorch', label: 'PyTorch' },
  { value: 'Python', label: 'Python' },
  { value: 'QlikView', label: 'QlikView' },
  { value: 'Quality Assurance', label: 'Quality Assurance' },
  { value: 'QuickBooks', label: 'QuickBooks' },
  { value: 'R', label: 'R' },
  { value: 'REST API', label: 'REST API' },
  { value: 'React Native', label: 'React Native' },
  { value: 'React.js', label: 'React.js' },
  { value: 'Reactjs Workflows', label: 'Reactjs Workflows' },
  { value: 'Recruiting', label: 'Recruiting' },
  { value: 'Redis', label: 'Redis' },
  { value: 'Redux', label: 'Redux' },
  { value: 'Research', label: 'Research' },
  { value: 'RethinkDB', label: 'RethinkDB' },
  { value: 'Risk Management', label: 'Risk Management' },
  { value: 'Ruby', label: 'Ruby' },
  { value: 'Ruby on Rails', label: 'Ruby on Rails' },
  { value: 'Rust', label: 'Rust' },
  { value: 'SEO', label: 'SEO' },
  { value: 'SIEM', label: 'SIEM' },
  { value: 'SOC', label: 'SOC' },
  { value: 'SQL', label: 'SQL' },
  { value: 'SQLite', label: 'SQLite' },
  { value: 'Sails.js', label: 'Sails.js' },
  { value: 'Sales', label: 'Sales' },
  { value: 'Scala', label: 'Scala' },
  { value: 'Scikit-learn', label: 'Scikit-learn' },
  { value: 'Scrum', label: 'Scrum' },
  { value: 'Shell', label: 'Shell' },
  { value: 'Sketch', label: 'Sketch' },
  { value: 'Social Media Marketing', label: 'Social Media Marketing' },
  { value: 'SolidWorks', label: 'SolidWorks' },
  { value: 'Sound Design', label: 'Sound Design' },
  { value: 'Spark', label: 'Spark' },
  { value: 'Spring Boot', label: 'Spring Boot' },
  { value: 'Styled Components', label: 'Styled Components' },
  { value: 'Substance Painter', label: 'Substance Painter' },
  { value: 'Supply Chain Management', label: 'Supply Chain Management' },
  { value: 'Svelte', label: 'Svelte' },
  { value: 'Swift', label: 'Swift' },
  { value: 'SwiftUI', label: 'SwiftUI' },
  { value: 'Symphony', label: 'Symphony' },
  { value: 'Tableau', label: 'Tableau' },
  { value: 'Tailwind CSS', label: 'Tailwind CSS' },
  { value: 'Talent Acquisition', label: 'Talent Acquisition' },
  { value: 'Tally', label: 'Tally' },
  { value: 'Tax Preparation', label: 'Tax Preparation' },
  { value: 'Team Leadership', label: 'Team Leadership' },
  { value: 'Technical Writing', label: 'Technical Writing' },
  { value: 'TensorFlow', label: 'TensorFlow' },
  { value: 'Terraform', label: 'Terraform' },
  { value: 'Time Management', label: 'Time Management' },
  { value: 'Translation', label: 'Translation' },
  { value: 'Travis CI', label: 'Travis CI' },
  { value: 'TypeScript', label: 'TypeScript' },
  { value: 'Typing', label: 'Typing' },
  { value: 'UI Design', label: 'UI Design' },
  { value: 'UX Research', label: 'UX Research' },
  { value: 'Unity', label: 'Unity' },
  { value: 'Unreal Engine', label: 'Unreal Engine' },
  { value: 'VBA', label: 'VBA' },
  { value: 'VPN', label: 'VPN' },
  { value: 'Vagrant', label: 'Vagrant' },
  { value: 'Vercel', label: 'Vercel' },
  { value: 'Video Editing', label: 'Video Editing' },
  { value: 'Vlogging', label: 'Vlogging' },
  { value: 'Vue.js', label: 'Vue.js' },
  { value: 'Vulnerability Assessment', label: 'Vulnerability Assessment' },
  { value: 'Wealth Management', label: 'Wealth Management' },
  { value: 'Webpack', label: 'Webpack' },
  { value: 'Wireframing', label: 'Wireframing' },
  { value: 'Writing', label: 'Writing' },
  { value: 'Xamarin', label: 'Xamarin' },
  { value: 'ZBrush', label: 'ZBrush' },
  { value: 'Zend Framework', label: 'Zend Framework' },
  { value: 'Zeplin', label: 'Zeplin' },
  { value: 'jQuery', label: 'jQuery' },
  { value: 'iOS Development', label: 'iOS Development' },
];

export const skillSuggestionsMap = {
  'React': ['React.js', 'React Native', 'Redux', 'Next.js', 'Reactjs Workflows', 'Frontend Development'],
  'React.js': ['React Native', 'Redux', 'Next.js', 'Reactjs Workflows', 'Frontend Development'],
  'JavaScript': ['TypeScript', 'Node.js', 'React.js', 'Vue.js', 'Angular', 'Frontend Development'],
  'Node.js': ['Express.js', 'MongoDB', 'REST API', 'Backend Development'],
  'Python': ['Django', 'Flask', 'Data Science', 'Machine Learning', 'Pandas'],
  'Java': ['Spring Boot', 'Hibernate', 'Microservices', 'Backend Development'],
  'HTML': ['CSS', 'Bootstrap', 'Tailwind CSS', 'Web Development'],
  'CSS': ['HTML', 'Bootstrap', 'Tailwind CSS', 'SASS'],
  'SQL': ['MySQL', 'PostgreSQL', 'Database Management', 'Oracle'],
  'MongoDB': ['Node.js', 'Express.js', 'NoSQL', 'Mongoose'],
  'AWS': ['Cloud Computing', 'Microsoft Azure', 'DevOps', 'Docker', 'Kubernetes'],
  'Figma': ['UI Design', 'UX Research', 'Adobe XD', 'Sketch', 'Wireframing'],
  'Adobe': ['Adobe Photoshop', 'Adobe Illustrator', 'Adobe Premiere Pro', 'Adobe After Effects', 'Adobe XD', 'Adobe InDesign', 'Adobe Lightroom'],
  'Video Editing': ['Adobe Premiere Pro', 'Final Cut Pro', 'DaVinci Resolve', 'Adobe After Effects'],
  'SEO': ['Content Marketing', 'Google Analytics', 'Google Ads', 'Digital Marketing'],
  'Accounting': ['Tally', 'QuickBooks', 'Bookkeeping', 'Financial Analysis', 'Excel'],
  'Finance': ['Financial Modeling', 'Corporate Finance', 'Accounting', 'Excel', 'Tally'],
  'Marketing': ['Digital Marketing', 'SEO', 'Social Media Marketing', 'Google Ads'],
  'HR': ['Recruiting', 'Talent Acquisition', 'Employee Relations', 'Onboarding'],
  'Cybersecurity': ['Ethical Hacking', 'Penetration Testing', 'Network Security', 'Cloud Security'],
  'Game Development': ['Unity', 'Unreal Engine', 'C#', 'C++']
};

export const getSuggestedSkills = (currentSkillsArray) => {
  if (!currentSkillsArray || currentSkillsArray.length === 0) return [];
  
  const suggestions = new Set();
  currentSkillsArray.forEach(skill => {
    Object.keys(skillSuggestionsMap).forEach(k => {
      if (k.toLowerCase().includes(skill.toLowerCase()) || skill.toLowerCase().includes(k.toLowerCase())) {
        skillSuggestionsMap[k].forEach(s => suggestions.add(s));
      }
    });
  });
  
  if (suggestions.size === 0) {
    return [];
  }
  
  return Array.from(suggestions).filter(s => !currentSkillsArray.includes(s)).slice(0, 8);
};
